### ISSUE TITLE
Package `newpxtext` is missing from 20250201

### ISSUE THREAD

**Issue by ranocha** [xu-cheng/latex-docker#23]
Thanks for your efforts! I have been using these containers together with https://github.com/xu-cheng/latex-action. Everything has worked smoothly so far. However, I have noticed that the [20250201](https://github.com/users/xu-cheng/packages/container/texlive-full/347394555?tag=20250201) version of the full image seems to be broken - it does not contain the package `newpxtext` anymore. Everything works again if I fix the docker version to

```
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          docker_image: ghcr.io/xu-cheng/texlive-full:20250101
```
